feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      stock-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
